# ----------------------------Web Mining Lab L29+L30+L47+L48---------------------------------

## ----------------------------------------------Digital Assignment Part-1 --------------------------------------------

### --------------------------------------------------------Faculty: Dr. Sanjiban Shekhar Roy-----------------------------------------------------------

##### ---------------------------------------------------------------------Venkata Raghu Ram Raavi - 19BCE2561----------------------------------------------------------------------------

#### 1.Create an array of 6 zeros

In [1]:
import numpy as np
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

#### 2.Create an array of 6 ones

In [2]:
import numpy as np
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

#### 3.Create an array of 6 fives

In [3]:
import numpy as np
np.ones(6)*5

array([5., 5., 5., 5., 5., 5.])

#### 4. Create an array of integers from 1 to 99

In [4]:
import numpy as np
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 5.Create an array of all the odd integers ranging from 1 to 99

In [5]:
import numpy as np
a = 100
arr2 = []

for i in range(a):
    if i %2 !=0:
        arr2.append(i)

arr2 = np.array(arr2)
arr2


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

#### 6. Create a 2X2 matrix filled with values from 1 to 4

In [6]:
import numpy as np
x =  np.arange(1, 5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

#### 7. Create a 3X3 matrix filled with values from 9 to 17

In [7]:
import numpy as np
x =  np.arange(9, 18).reshape(3,3)
x

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

#### 8. Make an indentity matrix of 4X4

In [8]:
import numpy as np
arr6 = np.identity(4, dtype = int)
print(arr6)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### 9.With the help of NumPy generate a random nos in between 0 to 1

In [9]:
import numpy as np

arr7 = np.random.randint(0, 1,5)
arr7

array([0, 0, 0, 0, 0])

#### 10. Create 10 points that are space linearly from each.

In [10]:
import numpy as np
x1 = np.linspace(0, 4,10)
x1

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

#### 11. Compare two 3d array and display the results in terms of true and false

In [11]:
import numpy as np
 
arr1 = np.random.randint(1, 8, size = (3, 5))
arr2 = np.random.randint(1, 9, size = (3, 5))
print('-----Two Dimensional Random Array----')
print('Values in arr1 = \n', arr1)
print('Values in arr2 = \n', arr2)
print('Result of arr1 == arr2 = \n', arr1 == arr2)
print('equal(arr1, arr2)   = \n', np.equal(arr1, arr2))
 
arr1 = np.random.randint(1, 8, size = (1, 2, 8))
arr2 = np.random.randint(1, 9, size = (1, 2, 8))
print('\n-----Three Dimensional Random Array----')
print('Values in arr1 = \n', arr1)
print('Values in arr2 = \n', arr2)
print('Result of arr1 == arr2      = \n', arr1 == arr2)
print('equal(arr1, arr2)   = \n', np.equal(arr1, arr2))

-----Two Dimensional Random Array----
Values in arr1 = 
 [[6 1 2 4 5]
 [6 3 2 1 5]
 [2 7 4 1 2]]
Values in arr2 = 
 [[4 7 4 2 8]
 [8 7 6 4 5]
 [6 5 2 8 6]]
Result of arr1 == arr2 = 
 [[False False False False False]
 [False False False False  True]
 [False False False False False]]
equal(arr1, arr2)   = 
 [[False False False False False]
 [False False False False  True]
 [False False False False False]]

-----Three Dimensional Random Array----
Values in arr1 = 
 [[[1 3 7 1 3 6 4 7]
  [7 4 6 6 3 5 4 2]]]
Values in arr2 = 
 [[[4 3 7 3 1 8 5 1]
  [7 1 8 4 8 3 2 1]]]
Result of arr1 == arr2      = 
 [[[False  True  True False False False False False]
  [ True False False False False False False False]]]
equal(arr1, arr2)   = 
 [[[False  True  True False False False False False]
  [ True False False False False False False False]]]


#### 12. Create a null vector of size 20 where the 6th value should be 0

In [12]:
import numpy as np
arr9 = np.arange(1,21)
print(arr9)
arr9[6] = 0
print("After Updating the 6th position")
print(arr9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After Updating the 6th position
[ 1  2  3  4  5  6  0  8  9 10 11 12 13 14 15 16 17 18 19 20]


#### 13. Reverse an array of size 100 using numpy.

In [13]:
import numpy as np

arr10 = np.arange(0,100)
arr10

arr10 = arr10[::-1]
arr10

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 14. Find the minimum and maximum values of a 20X20 array using numpy

In [14]:
import numpy as np
arr11 = np.arange(0,400)
arr11.reshape(20,20)
print(arr11)
print("\n")
print("The maximum value in 20*20 array: ",max(arr11))
print("\n")
print("The minimum value in 20*20 array: ",min(arr11))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 15. Find mean value of a randomly generated array of size 50

In [15]:
import numpy as np

arr12  = np.random.randint(0,50,size= 50)
print(arr12)
print("\n")
print("Size of randomly generated array: ",len(arr12))
print("\n")
x = np.mean(arr12)
print("mean value of a randomly generated array of size 50: ",x)

[19 25 22  3 29 10 48 47  1 49 34 46 33  5  1  2  2 10 23 39 30  6 32 12
 14 47 19 46 14 41 26 22 47 33  9 38 39 41 14 48 28 38 48 31 19  7 46  8
 41 44]


Size of randomly generated array:  50


mean value of a randomly generated array of size 50:  26.72


#### 16. “ A 20 X20 array filled with zeros at all borders and all 1’s inside”-create such array.

In [16]:
import numpy as np

arr13 = np.zeros((20,20))
print("Original array:")
print("\n")
print(arr13)
print("\n")
print("A 20 X20 array filled with zeros at all borders and all 1’s inside")
print("\n")
arr13[1:-1,1:-1] = 1
print(arr13)

Original array:


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 17. Create an array of size 10X10 with 10 element valued as nan

In [17]:
import numpy as np
import numpy as np

arr13 = np.empty((10,10))
arr13[:] = np.NaN
print(arr13)

[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


#### 18. Create a 4X4 matrix and the values just below the diagonal is 9 8 7

In [18]:
import numpy as np
arr14 = np.ones((4,4),dtype = int)
print("Before Updating the Diagnoal Elements:")
print("\n",arr14)
arr14 = np.diag([9,8,7],-1)
print("\nAfter Updating")
print("\n",arr14)

Before Updating the Diagnoal Elements:

 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

After Updating

 [[0 0 0 0]
 [9 0 0 0]
 [0 8 0 0]
 [0 0 7 0]]


#### 19. Create a check board pattern using numpy

In [19]:
chess_board = np.ones((8,8),dtype=int)
chess_board[1::2, ::2]= 0
chess_board[::2, 1::2] = 0
print(chess_board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Print the dtype of int32 and float64 data type.

In [20]:
arr2 = np.array([2,4,5,6,7,8,7,9,56], dtype = np.float64)
arr2.dtype

dtype('float64')

In [21]:
arr3 = np.array([2,4,5,6,7,8,7,9,56], dtype = np.int32)
arr3.dtype

dtype('int32')