## ----------------------------------------------Digital Assignment Part-2 --------------------------------------------

### Questions
1. An empty numpy array
2. Numpy array filled with all zeros
3. Check a Numpy array has a particular row
4. Delete elements (+ve) values from a NumPy array
5. How to find a particular sequences has occurred in a Numpy Array
6. Search a maximum no of element that is there in a numpy array
7. Is is possible to merge two 2 dimentional array(numpy)?Do then.
8. Can you add a border of a numpy array?Do then.
9. A comparison of two numpy array
10. Find diagonal of 2D numpy array

#### 1. An empty numpy array

In [1]:
import numpy as np

arr1 = np.empty((5,5))
arr1

array([[4.67296746e-307, 1.69121096e-306, 1.02359984e-306,
        1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.33511018e-306,
        6.23057689e-307, 1.33511290e-306],
       [1.78019082e-306, 8.45559303e-307, 8.06613040e-308,
        6.89810244e-307, 1.22387550e-307],
       [2.22522596e-306, 8.34423917e-308, 1.11261162e-306,
        1.78021527e-306, 9.11571040e-304]])

#### 2. Numpy array filled with all zeros

In [2]:
import numpy as np
arr2 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 3. Check a Numpy array has a particular row

In [3]:
import numpy as np
arr3  = np.arange(9).reshape(3,3)
arr3
print([0,1,2] in arr3.tolist())
print([2,56.560,58] in arr3.tolist())

True
False


#### 4. Delete elements (+ve) values from a NumPy array

In [4]:
import numpy as np  ## needed to improve the program needed to modify
arr4 = np.arange(16).reshape(4,4)
print("Before deleting the elements from the numpy array: ")
print("\n")
print(arr4)
arr5 = np.delete(arr4,0,axis = 0)
print("\nAfter Deleting the elements from the numpy array: ")
print("\n",arr5)

Before deleting the elements from the numpy array: 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After Deleting the elements from the numpy array: 

 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 5. How to find a particular sequences has occurred in a Numpy Array

In [5]:
import numpy as np
arr3 = ([2,3,4,5,6,7,8,9,7,5,4,4,5,6,7,8,5,5,4,3,3,3,3,33,44,5,55,5,5,5,5]) # single dimensions
arr3 = np.array(arr3) 

count = np.count_nonzero(arr3 == 3)

print('The number of occurances of number 3 in arr3: ',count) ## we are using the count_nonzero() function to get the no of occurances

count1 = np.bincount(arr3)
print('The number of occurances of number 5 in arr3: ',count1[5]) # we are using the bincount() inbuilt function to get the occurances


The number of occurances of number 3 in arr3:  5
The number of occurances of number 5 in arr3:  10


##### Using  Two dimensional array

In [6]:
import numpy as np
arr5 = np.array([[4,5,6,666], 
                   [666,666,666,6666],
                   [4334, 4445, 666, 7]])
  
count4 = np.count_nonzero("666")
print(count4)

1


#### 6. Search a maximum no of element that is there in a numpy array

In [7]:
import numpy as np
arr5 = np.array([[4,5,6,666], 
                   [666,666,666,6666],
                   [4334, 4445, 666, 7]])

a = np.max(arr5)
print('the maximum value in the arr5 is: ',a)

the maximum value in the arr5 is:  6666


#### 7. Is is possible to merge two 2 dimentional array(numpy)?Do then.

In [8]:
import numpy as np

arr14 = np.array([14,67,56,45,34,67,89,77])
arr15 = np.array([67,78,56,45,34,56,78,90])

arr16 = np.concatenate((arr14,arr15))

print(arr16)

[14 67 56 45 34 67 89 77 67 78 56 45 34 56 78 90]


#### 8. Can you add a border of a numpy array?Do then.

In [9]:
## we can add the border to the numpy array we can addd twos as borders to the array with fives inside the array.

import numpy as np
arr13 = np.ones((5,5))*2
print("Original array:")
print("\n")
print(arr13)
print("\n")
print("After adding border: ")
print("\n")
arr13[1:-1,1:-1] =5
print(arr13)

Original array:


[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


After adding border: 


[[2. 2. 2. 2. 2.]
 [2. 5. 5. 5. 2.]
 [2. 5. 5. 5. 2.]
 [2. 5. 5. 5. 2.]
 [2. 2. 2. 2. 2.]]


#### 9. A comparison of two numpy array

In [10]:
import numpy as np
  
arr16 = np.array([[11,12,14,15,16],
                  [11,12,13,14,15],
                 [56,57,58,59,60],
                 [61,62,63,64,64],
                 [71,72,73,74,75]])

arr17 = np.array([[11,12,14,15,16], 
              [11,12,14,14,15],
             [56,57,58,59,60],
             [61,62,63,64,64],
             [71,72,73,74,75]])

arr18 = np.array([[11,12,14,15,16], 
                  [11,12,13,14,15],
                 [56,57,58,59,60],
                 [61,62,63,64,64],
                 [71,72,73,74,75]])


a = (arr16 == arr17).all() ##we are using this .all() so that it checks each and every element in the numpy array
b = (arr16 == arr18).all()
c = (arr17 == arr18).all()
print(a)
print(b)
print(c)

False
True
False


#### 10. Find diagonal of 2D numpy array

In [11]:
import numpy as np
arr20 = np.array([[4,5,6],
                  [66,66,44],
                 [333,444,555]])
  
a= arr20.shape
print(np.diag(arr20))

[  4  66 555]
